//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal
{


    public partial class recruiter_dashboard
    {
        /// <summary>
        /// lblRecruiterName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRecruiterName;

        /// <summary>
        /// lblCurrentDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentDate;

        /// <summary>
        /// lblCompanyName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCompanyName;

        /// <summary>
        /// lblTotalJobs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalJobs;

        /// <summary>
        /// lblActiveJobs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveJobs;

        /// <summary>
        /// lblApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApplications;

        /// <summary>
        /// lblShortlisted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShortlisted;

        /// <summary>
        /// pnlRecentApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRecentApplications;

        /// <summary>
        /// rptRecentApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentApplications;

        /// <summary>
        /// pnlNoApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoApplications;

        /// <summary>
        /// pnlActiveJobs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlActiveJobs;

        /// <summary>
        /// rptActiveJobs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActiveJobs;

        /// <summary>
        /// pnlNoActiveJobs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoActiveJobs;

        /// <summary>
        /// lblAvgApplications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvgApplications;

        /// <summary>
        /// lblHiredCandidates control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHiredCandidates;

        /// <summary>
        /// lblPendingReview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingReview;

        /// <summary>
        /// lblProfileViews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileViews;

        /// <summary>
        /// lblResponseRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResponseRate;

        /// <summary>
        /// lblCompletionRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCompletionRate;

        /// <summary>
        /// lblSatisfactionRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSatisfactionRate;
    }
}
